# Generated by Django 6.0.2 on 2026-03-05 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_creator_quiz_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text questions')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок питання')),
                ('hours', models.IntegerField(default=0, verbose_name='Годин')),
                ('minutes', models.IntegerField(default=1, verbose_name='Хвилин')),
                ('seconds', models.IntegerField(default=0, verbose_name='Секунд')),
                ('has_time_limit', models.BooleanField(default=True, verbose_name='Має обмеження часу')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz', verbose_name='Вікторина')),
            ],
            options={
                'verbose_name': 'Питання',
                'verbose_name_plural': 'Питання',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст відповіді')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильна відповідь')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.question', verbose_name='Питання')),
            ],
            options={
                'verbose_name': 'Відповідь',
                'verbose_name_plural': 'Відповіді',
            },
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Початок')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершення')),
                ('score', models.IntegerField(default=0, verbose_name='Бали')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quizzes.quiz', verbose_name='Вікторина')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Сесія вікторини',
                'verbose_name_plural': 'Сесії вікторин',
                'unique_together': {('quiz', 'user', 'is_completed')},
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('time_spent', models.IntegerField(default=0, verbose_name='Час на відповідь (сек)')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Час відповіді')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.answer', verbose_name='Відповідь')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.question', verbose_name='Питання')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.quizsession', verbose_name='Сесія')),
            ],
            options={
                'verbose_name': 'Відповідь користувача',
                'verbose_name_plural': 'Відповіді користувачів',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
