# Generated by Django 6.0.2 on 2026-03-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_quiz_options_question_answer_quizsession_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='has_time_limit',
        ),
        migrations.RemoveField(
            model_name='question',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='question',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='seconds',
        ),
        migrations.AddField(
            model_name='quiz',
            name='has_time_limit',
            field=models.BooleanField(default=True, verbose_name='Має обмеження часу'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='hours',
            field=models.IntegerField(default=0, verbose_name='Годин'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='minutes',
            field=models.IntegerField(default=1, verbose_name='Хвилин'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='seconds',
            field=models.IntegerField(default=0, verbose_name='Секунд'),
        ),
    ]
